spring:
  application:
    name: ${SPRING_APPLICATION_NAME}
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  
  # Configuración común de Redis
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}
      password: ${SPRING_DATA_REDIS_PASSWORD}
      database: ${SPRING_DATA_REDIS_DATABASE}
      timeout: ${SPRING_DATA_REDIS_TIMEOUT}
      ssl:
        enabled: ${SPRING_DATA_REDIS_SSL_ENABLED}

# Configuración común de Resilience4j
resilience4j:
  circuitbreaker:
    instances:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
  ratelimiter:
    instances:
      default:
        limitForPeriod: 100
        limitRefreshPeriod: 1s
        timeoutDuration: 5s

# Configuración de métricas y monitoreo
management:
  endpoint:
    health:
      show-details: always
      group:
        readiness:
          include: readinessState,db,eventstore,kafka
        liveness:
          include: livenessState
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5,0.75,0.95,0.99
    web:
      server:
        request:
          autotime:
            enabled: true
  health:
    redis:
      enabled: true
    mongo:
      enabled: true
    kafka:
      enabled: true
      topic-verification:
        enabled: true

# Configuración de logging
logging:
  level:
    root: INFO
    org.springframework: INFO
    com.fantasy.sport: DEBUG
    org.springframework.data.mongodb.core.ReactiveMongoTemplate: DEBUG
    org.springframework.kafka: INFO
    reactor.kafka: INFO
    com.eventstore: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
