# Configuración específica para desarrollo
server:
  port: ${SERVER_PORT_DEV}

spring:
  config:
    activate:
      on-profile: dev
  data:
    mongodb:
      host: ${SPRING_DATA_MONGODB_HOST}
      port: ${SPRING_DATA_MONGODB_PORT}
      database: ${SPRING_DATA_MONGODB_DATABASE:${SPRING_DATA_MONGODB_DATABASE_DEV}}
      authentication-database: ${SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE}
      username: ${SPRING_DATA_MONGODB_USERNAME:${SPRING_DATA_MONGODB_USERNAME_DEV}}
      password: ${SPRING_DATA_MONGODB_PASSWORD:${SPRING_DATA_MONGODB_PASSWORD_DEV}}
      auto-index-creation: ${SPRING_DATA_MONGODB_AUTO_INDEX_CREATION}

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:}
    consumer:
      group-id: ${SPRING_KAFKA_CONSUMER_GROUP_ID}
      auto-offset-reset: ${SPRING_KAFKA_CONSUMER_AUTO_OFFSET_RESET}
      key-deserializer: ${SPRING_KAFKA_CONSUMER_KEY_DESERIALIZER}
      value-deserializer: ${SPRING_KAFKA_CONSUMER_VALUE_DESERIALIZER}
      properties:
        "[spring.json.trusted.packages]": "${SPRING_KAFKA_CONSUMER_PROPERTIES_TRUSTED_PACKAGES:*}"
    producer:
      key-serializer: ${SPRING_KAFKA_PRODUCER_KEY_SERIALIZER}
      value-serializer: ${SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER}
      
  # Configuración de Redis para desarrollo
  data.redis:
    host: ${SPRING_DATA_REDIS_HOST}
    port: ${SPRING_DATA_REDIS_PORT}
    password: ${SPRING_DATA_REDIS_PASSWORD}
    database: ${SPRING_DATA_REDIS_DATABASE}
    timeout: ${SPRING_DATA_REDIS_TIMEOUT}  # 2 segundos de timeout
    ssl:
      enabled: ${SPRING_DATA_REDIS_SSL_ENABLED}

# Configuración de EventStoreDB para desarrollo
eventstore:
  connection-string: ${EVENTSTORE_CONNECTION_STRING:esdb://${EVENTSTORE_USERNAME}:${EVENTSTORE_PASSWORD}@${EVENTSTORE_HOST}:${EVENTSTORE_HTTP_PORT}?tls=${EVENTSTORE_TLS}}
  http-port: ${EVENTSTORE_HTTP_PORT}
  tcp-port: ${EVENTSTORE_TCP_PORT}
  username: ${EVENTSTORE_USERNAME}
  password: ${EVENTSTORE_PASSWORD}
  max-discovery-attempts: ${EVENTSTORE_MAX_DISCOVERY_ATTEMPTS}
  discovery-interval-ms: ${EVENTSTORE_DISCOVERY_INTERVAL_MS}

# Health check configuration
management:
  endpoint:
    health:
      group:
        readiness:
          include: readinessState,db,eventstore,kafka
  health:
    eventstore:
      enabled: true

# Configuración de logging para desarrollo
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
    org.springframework.data.mongodb.core.ReactiveMongoTemplate: DEBUG
    org.springframework.kafka: DEBUG
    reactor.kafka: DEBUG
    com.eventstore: DEBUG
